language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "iojs"
before_install: npm install -g grunt-cli
install: npm install
notifications:
  slack:
    secure: eWKjw1J4ua7e6/USQwcJOLiJXBTrgF+5sELqKcUsGVTvnzuflmvUDBk0opx8zpfOdSotWbk8+r2zvT0KWDNQGBhUTmjROkfNd+n6+n8xl6/LkyhDWSImK39ljKmreOfI+a9M3rQcw9rwt1WyIfqkOmna8utffuzIAXOH0QAtiAQ=
